version: "3"

vars:
  GO: go


tasks:
  default: run

  run: 
    cmds:
      - task: build_generic
        vars:
          GOOS: '{{OS}}'
          GOARCH: '{{ARCH}}'
      - ./bin/wakeonlan_{{OS}}_{{ARCH}}{{exeExt}}

  build:
    cmds:
      - task: build_generic
        vars:
          GOOS: '{{OS}}'
          GOARCH: '{{ARCH}}'

  build_all:
    cmds:
      - task: build_generic
        vars:
          GOOS: 'windows'
          GOARCH: 'amd64'
      - task: build_generic
        vars:
          GOOS: 'linux'
          GOARCH: 'amd64' 
      - task: build_generic
        vars:
          GOOS: 'linux'
          GOARCH: 'arm64'                 

  build_generic: 
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
    generates:
      - ./bin/wakeonlan_{{.GOOS}}_{{.GOARCH}}{{if eq .GOOS "windows"}}.exe{{end}}
    sources:
      - main.go
      - pkg/*/*.go
    deps:
      - embedFS 
      - go-setup
    cmds:
      - go build -o bin/wakeonlan_{{.GOOS}}_{{.GOARCH}}{{if eq .GOOS "windows"}}.exe{{end}}

  

  go-setup: #go.sum embedfs/
    sources:
      - go.mod
    generates:
      - go.sum
    cmds:
      - go mod tidy
      - go mod download
      - go mod verify
      - go get github.com/UnnoTed/fileb0x

  embedFS: 
    deps:
      - go-setup
    sources:
      - views/*
      - assets/*
    generates:
      - embedFS/*
    cmds:
      - go generate
