# This is a basic workflow that is manually triggered

name: Build manual

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Setup deps and build embedFS
        run: task build-deps
      - name: Build
        run: task build-all-concurrent
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/*
          draft: true
          
