# This is a basic workflow that is manually triggered

name: Build manual

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - name: Install Taskfile
        run: curl -sL https://taskfile.dev/install.sh | sh
      - name: Build
        run: task build_all
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          release_name: $ { { steps.version.outputs.version }}
          tag_name: $ { { github.ref }}
          #body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: $ { { github.token }}
      - name: Upload win artifact 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: $ { { github.token }}
        with:
          upload_url: $ { { steps.create_release.outputs.upload_url }}
          asset_path: ./bin/*
          #asset_name: my-artifact-1
          asset_content_type: application/octet-stream
        
